### ISSUE TITLE
Init environment variables

### ISSUE THREAD

**Issue by pdf** [socrata-cookbooks/dnsmasq-local#13]
The init script on Debian/Ubuntu makes some questionable decisions (eg [lp:1042275](https://bugs.launchpad.net/ubuntu/+source/dnsmasq/+bug/1042275) and others), and the only way to fix them is to set vars in `/etc/default/dnsmasq` (eg `DNSMASQ_EXCEPT`, `IGNORE_RESOLVCONF`), however since that's controlled by this cookbook there's no way to set them currently.

**Comment by RoboticCheese** [comment]
If I'm reading the init script right, both of these environment variables end up passing additional options to the dnsmasq command. Those can be set through the service resource as it exists now. So something like:

```ruby
dnsmasq_local_service 'default' do
  except_interface 'eth1'
  resolv_file '/path/to/some/other/resolv.conf'
end
```

or:

```ruby
dnsmasq_local_service 'default' do
  options(except_interface: 'eth1', resolv_file: '/path/to/some/other/resolv.conf')
end
```

or via the `node['dnsmasq_local']['options']` attribute when doing a recipe-driven install.

**Comment by pdf** [comment]
The problem is that the init script adds its own arguments depending on the env var values.

**Comment by RoboticCheese** [comment]
Oof. I missed those ugly conditional blocks in there.

**Comment by RoboticCheese** [comment]
Added an environment property+attribute via #17. This'll be in the 2.0.0 release as well.
