### ISSUE TITLE
Multiple `dnsmasq_local_config` calls

### ISSUE THREAD

**Issue by pdf** [socrata-cookbooks/dnsmasq-local#14]
Seems like as a provider, we should be able to call `dnsmasq_local_config` with a different name and contents to create multiple resources.  A sensible method for handling this might be to generate a file per resource in `/etc/dnsmasq.d`, named to match the resource.  So:

``` ruby
dnsmasq_local_config 'default' do
  action :create
end
dnsmasq_local_config 'something' do
  action :create
end
```

Would generate `/etc/dnsmasq.d/default.conf` and `/etc/dnsmasq.d/something.conf`.

This allows composing a dnsmasq config from multiple recipies.  For example, we have hosts that need to forward domains to another service, but only when they have a certain recipe in their run-list.

**Comment by RoboticCheese** [comment]
A `filename` property has been added that by default derives from the resource name. So, a `/etc/dnsmasq.d/thing.conf` file could be created with either:

```ruby
dnsmasq_local_config 'thing'
```

or:

```ruby
dnsmasq_local_config 'default' do
  filename 'thing.conf'
end
```

This change is merged into master and will be a part of the 2.0.0 release.
